//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloryDemo {
    using System.Collections.Generic;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Glory", "0.1.0.0")]
    internal class ExpressionParser : GlrTableParser {
        internal static int[][][][] ParseTable = new int[][][][] {
                new int[][][] {
                        new int[][] {
                                new int[] {
                                        1}},
                        new int[][] {
                                new int[] {
                                        2}},
                        new int[][] {
                                new int[] {
                                        6}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        -1}}},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        3}},
                        null,
                        new int[][] {
                                new int[] {
                                        28}},
                        new int[][] {
                                new int[] {
                                        30}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        1,
                                        0,
                                        1}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        1,
                                        0,
                                        1}}},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        4}},
                        new int[][] {
                                new int[] {
                                        26}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        0,
                                        0,
                                        1,
                                        4}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        0,
                                        0,
                                        1,
                                        4}}},
                new int[][][] {
                        null,
                        new int[][] {
                                new int[] {
                                        5}},
                        new int[][] {
                                new int[] {
                                        6}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10,
                                        4,
                                        4,
                                        6,
                                        1}},
                        new int[][] {
                                new int[] {
                                        10,
                                        4,
                                        4,
                                        6,
                                        1}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10,
                                        4,
                                        4,
                                        6,
                                        1}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10,
                                        4,
                                        4,
                                        6,
                                        1}}},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        7}},
                        new int[][] {
                                new int[] {
                                        3,
                                        1,
                                        2}},
                        new int[][] {
                                new int[] {
                                        3,
                                        1,
                                        2}},
                        new int[][] {
                                new int[] {
                                        22}},
                        new int[][] {
                                new int[] {
                                        24}},
                        null,
                        new int[][] {
                                new int[] {
                                        3,
                                        1,
                                        2}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        3,
                                        1,
                                        2}}},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        2,
                                        1,
                                        2,
                                        5}},
                        new int[][] {
                                new int[] {
                                        2,
                                        1,
                                        2,
                                        5}},
                        new int[][] {
                                new int[] {
                                        8}},
                        new int[][] {
                                new int[] {
                                        20}},
                        null,
                        new int[][] {
                                new int[] {
                                        2,
                                        1,
                                        2,
                                        5}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        2,
                                        1,
                                        2,
                                        5}}},
                new int[][][] {
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        9}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        14,
                                        5,
                                        5,
                                        8,
                                        2}},
                        new int[][] {
                                new int[] {
                                        14,
                                        5,
                                        5,
                                        8,
                                        2}},
                        new int[][] {
                                new int[] {
                                        14,
                                        5,
                                        5,
                                        8,
                                        2}},
                        new int[][] {
                                new int[] {
                                        14,
                                        5,
                                        5,
                                        8,
                                        2}},
                        null,
                        new int[][] {
                                new int[] {
                                        14,
                                        5,
                                        5,
                                        8,
                                        2}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        14,
                                        5,
                                        5,
                                        8,
                                        2}}},
                new int[][][] {
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        11}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        4,
                                        2,
                                        6,
                                        2}},
                        new int[][] {
                                new int[] {
                                        4,
                                        2,
                                        6,
                                        2}},
                        new int[][] {
                                new int[] {
                                        4,
                                        2,
                                        6,
                                        2}},
                        new int[][] {
                                new int[] {
                                        4,
                                        2,
                                        6,
                                        2}},
                        null,
                        new int[][] {
                                new int[] {
                                        4,
                                        2,
                                        6,
                                        2}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        4,
                                        2,
                                        6,
                                        2}}},
                new int[][][] {
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        13}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        5,
                                        2,
                                        7,
                                        2}},
                        new int[][] {
                                new int[] {
                                        5,
                                        2,
                                        7,
                                        2}},
                        new int[][] {
                                new int[] {
                                        5,
                                        2,
                                        7,
                                        2}},
                        new int[][] {
                                new int[] {
                                        5,
                                        2,
                                        7,
                                        2}},
                        null,
                        new int[][] {
                                new int[] {
                                        5,
                                        2,
                                        7,
                                        2}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        5,
                                        2,
                                        7,
                                        2}}},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        6,
                                        2,
                                        3}},
                        new int[][] {
                                new int[] {
                                        6,
                                        2,
                                        3}},
                        new int[][] {
                                new int[] {
                                        6,
                                        2,
                                        3}},
                        new int[][] {
                                new int[] {
                                        6,
                                        2,
                                        3}},
                        null,
                        new int[][] {
                                new int[] {
                                        6,
                                        2,
                                        3}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        6,
                                        2,
                                        3}}},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        7,
                                        3,
                                        12}},
                        new int[][] {
                                new int[] {
                                        7,
                                        3,
                                        12}},
                        new int[][] {
                                new int[] {
                                        7,
                                        3,
                                        12}},
                        new int[][] {
                                new int[] {
                                        7,
                                        3,
                                        12}},
                        null,
                        new int[][] {
                                new int[] {
                                        7,
                                        3,
                                        12}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        7,
                                        3,
                                        12}}},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        8,
                                        3,
                                        13}},
                        new int[][] {
                                new int[] {
                                        8,
                                        3,
                                        13}},
                        new int[][] {
                                new int[] {
                                        8,
                                        3,
                                        13}},
                        new int[][] {
                                new int[] {
                                        8,
                                        3,
                                        13}},
                        null,
                        new int[][] {
                                new int[] {
                                        8,
                                        3,
                                        13}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        8,
                                        3,
                                        13}}},
                new int[][][] {
                        new int[][] {
                                new int[] {
                                        18}},
                        new int[][] {
                                new int[] {
                                        2}},
                        new int[][] {
                                new int[] {
                                        6}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        19}},
                        null,
                        null,
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        9,
                                        3,
                                        10,
                                        0,
                                        11}},
                        new int[][] {
                                new int[] {
                                        9,
                                        3,
                                        10,
                                        0,
                                        11}},
                        new int[][] {
                                new int[] {
                                        9,
                                        3,
                                        10,
                                        0,
                                        11}},
                        new int[][] {
                                new int[] {
                                        9,
                                        3,
                                        10,
                                        0,
                                        11}},
                        null,
                        new int[][] {
                                new int[] {
                                        9,
                                        3,
                                        10,
                                        0,
                                        11}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        9,
                                        3,
                                        10,
                                        0,
                                        11}}},
                new int[][][] {
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        21}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        15,
                                        5,
                                        5,
                                        9,
                                        2}},
                        new int[][] {
                                new int[] {
                                        15,
                                        5,
                                        5,
                                        9,
                                        2}},
                        new int[][] {
                                new int[] {
                                        15,
                                        5,
                                        5,
                                        9,
                                        2}},
                        new int[][] {
                                new int[] {
                                        15,
                                        5,
                                        5,
                                        9,
                                        2}},
                        null,
                        new int[][] {
                                new int[] {
                                        15,
                                        5,
                                        5,
                                        9,
                                        2}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        15,
                                        5,
                                        5,
                                        9,
                                        2}}},
                new int[][][] {
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        23}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        16,
                                        5,
                                        8,
                                        2}},
                        new int[][] {
                                new int[] {
                                        16,
                                        5,
                                        8,
                                        2}},
                        new int[][] {
                                new int[] {
                                        16,
                                        5,
                                        8,
                                        2}},
                        new int[][] {
                                new int[] {
                                        16,
                                        5,
                                        8,
                                        2}},
                        null,
                        new int[][] {
                                new int[] {
                                        16,
                                        5,
                                        8,
                                        2}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        16,
                                        5,
                                        8,
                                        2}}},
                new int[][][] {
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        25}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17,
                                        5,
                                        9,
                                        2}},
                        new int[][] {
                                new int[] {
                                        17,
                                        5,
                                        9,
                                        2}},
                        new int[][] {
                                new int[] {
                                        17,
                                        5,
                                        9,
                                        2}},
                        new int[][] {
                                new int[] {
                                        17,
                                        5,
                                        9,
                                        2}},
                        null,
                        new int[][] {
                                new int[] {
                                        17,
                                        5,
                                        9,
                                        2}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17,
                                        5,
                                        9,
                                        2}}},
                new int[][][] {
                        null,
                        new int[][] {
                                new int[] {
                                        27}},
                        new int[][] {
                                new int[] {
                                        6}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        11,
                                        4,
                                        4,
                                        7,
                                        1}},
                        new int[][] {
                                new int[] {
                                        11,
                                        4,
                                        4,
                                        7,
                                        1}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        11,
                                        4,
                                        4,
                                        7,
                                        1}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        11,
                                        4,
                                        4,
                                        7,
                                        1}}},
                new int[][][] {
                        null,
                        new int[][] {
                                new int[] {
                                        29}},
                        new int[][] {
                                new int[] {
                                        6}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        12,
                                        4,
                                        6,
                                        1}},
                        new int[][] {
                                new int[] {
                                        12,
                                        4,
                                        6,
                                        1}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        12,
                                        4,
                                        6,
                                        1}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        12,
                                        4,
                                        6,
                                        1}}},
                new int[][][] {
                        null,
                        new int[][] {
                                new int[] {
                                        31}},
                        new int[][] {
                                new int[] {
                                        6}},
                        new int[][] {
                                new int[] {
                                        14}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        10}},
                        new int[][] {
                                new int[] {
                                        12}},
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        17}},
                        null,
                        new int[][] {
                                new int[] {
                                        15}},
                        new int[][] {
                                new int[] {
                                        16}},
                        null,
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        13,
                                        4,
                                        7,
                                        1}},
                        new int[][] {
                                new int[] {
                                        13,
                                        4,
                                        7,
                                        1}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        13,
                                        4,
                                        7,
                                        1}},
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        13,
                                        4,
                                        7,
                                        1}}}};
        internal static string[] SymbolTable = new string[] {
                "Term",
                "Factor",
                "Unary",
                "Leaf",
                "TermList",
                "FactorList",
                "add",
                "sub",
                "mul",
                "div",
                "lparen",
                "rparen",
                "integer",
                "identifier",
                "whitespace",
                "#EOS",
                "#ERROR"};
        internal static ParseAttribute[][] ParseAttributes = new ParseAttribute[][] {
                new ParseAttribute[] {
                        new ParseAttribute("type", "int"),
                        new ParseAttribute("start", true)},
                new ParseAttribute[] {
                        new ParseAttribute("type", "int")},
                new ParseAttribute[] {
                        new ParseAttribute("type", "int")},
                new ParseAttribute[] {
                        new ParseAttribute("type", "int")},
                new ParseAttribute[] {
                        new ParseAttribute("collapsed", true),
                        new ParseAttribute("nowarn", true),
                        new ParseAttribute("factored", true)},
                new ParseAttribute[] {
                        new ParseAttribute("collapsed", true),
                        new ParseAttribute("nowarn", true),
                        new ParseAttribute("factored", true)},
                new ParseAttribute[] {
                        new ParseAttribute("terminal", true)},
                new ParseAttribute[] {
                        new ParseAttribute("terminal", true)},
                new ParseAttribute[] {
                        new ParseAttribute("terminal", true)},
                new ParseAttribute[] {
                        new ParseAttribute("terminal", true)},
                new ParseAttribute[] {
                        new ParseAttribute("terminal", true)},
                new ParseAttribute[] {
                        new ParseAttribute("terminal", true)},
                new ParseAttribute[] {
                        new ParseAttribute("terminal", true)},
                new ParseAttribute[] {
                        new ParseAttribute("terminal", true)},
                new ParseAttribute[] {
                        new ParseAttribute("hidden", true)},
                new ParseAttribute[0],
                new ParseAttribute[0]};
        internal static int[] ErrorSentinels = new int[0];
        public ExpressionParser(IEnumerable<Token> tokenizer) : 
                base(ExpressionParser.ParseTable, ExpressionParser.SymbolTable, ExpressionParser.ParseAttributes, ExpressionParser.ErrorSentinels, tokenizer, int.MaxValue) {
        }
        public ExpressionParser(IEnumerable<Token> tokenizer, int maxErrorCount) : 
                base(ExpressionParser.ParseTable, ExpressionParser.SymbolTable, ExpressionParser.ParseAttributes, ExpressionParser.ErrorSentinels, tokenizer, maxErrorCount) {
        }
        /// <summary>
        /// Evaluates a derivation of the form:
        /// Term= Factor { ( "+" | "-" ) Factor }
        /// </summary>
        /// <remarks>
        /// The production rules are:
        /// Term -> Factor TermList
        /// Term -> Factor
        /// </remarks>
        /// <param name="node">The <see cref="ParseNode"/> to evaluate</param>
        /// <returns>The result of the evaluation</returns>
        public static int Evaluate(ParseNode node) {
            return ExpressionParser.EvaluateTerm(node, null);
        }
        /// <summary>
        /// Evaluates a derivation of the form:
        /// Term= Factor { ( "+" | "-" ) Factor }
        /// </summary>
        /// <remarks>
        /// The production rules are:
        /// Term -> Factor TermList
        /// Term -> Factor
        /// </remarks>
        /// <param name="node">The <see cref="ParseNode"/> to evaluate</param>
        /// <param name="state">A user supplied state object. What it should be depends on the production's associated code block</param>
        /// <returns>The result of the evaluation</returns>
        public static int Evaluate(ParseNode node, object state) {
            return ExpressionParser.EvaluateTerm(node, state);
        }
        /// <summary>
        /// Evaluates a derivation of the form:
        /// Term= Factor { ( "+" | "-" ) Factor }
        /// </summary>
        /// <remarks>
        /// The production rules are:
        /// Term -> Factor TermList
        /// Term -> Factor
        /// </remarks>
        /// <param name="node">The <see cref="ParseNode"/> to evaluate</param>
        /// <param name="state">A user supplied state object. What it should be depends on the production's associated code block</param>
        /// <returns>The result of the evaluation</returns>
        internal static int EvaluateTerm(ParseNode node, object state) {
            int result = ExpressionParser.EvaluateFactor(node.Children[0], state);
            int i = 2;
            for (
            ; (i < node.Children.Length); 
            ) {
                if ((node.Children[(i - 1)].SymbolId == GloryDemo.ExpressionParser.add)) {
                    result = (result + ExpressionParser.EvaluateFactor(node.Children[i], state));
                }
                else {
                    result = (result - ExpressionParser.EvaluateFactor(node.Children[i], state));
                }
                i = (i + 2);
            }
            return ((int)(ExpressionParser._ChangeType(result, typeof(int))));
        }
        /// <summary>
        /// Evaluates a derivation of the form:
        /// Factor= Unary { ( "*" | "/" ) Unary }
        /// </summary>
        /// <remarks>
        /// The production rules are:
        /// Factor -> Unary FactorList
        /// Factor -> Unary
        /// </remarks>
        /// <param name="node">The <see cref="ParseNode"/> to evaluate</param>
        /// <param name="state">A user supplied state object. What it should be depends on the production's associated code block</param>
        /// <returns>The result of the evaluation</returns>
        internal static int EvaluateFactor(ParseNode node, object state) {
            int result = ExpressionParser.EvaluateUnary(node.Children[0], state);
            int i = 2;
            for (
            ; (i < node.Children.Length); 
            ) {
                if ((node.Children[(i - 1)].SymbolId == GloryDemo.ExpressionParser.mul)) {
                    result = (result * ((int)(ExpressionParser._EvaluateAny(node.Children[i], state))));
                }
                else {
                    result = (result / ((int)(ExpressionParser._EvaluateAny(node.Children[i], state))));
                }
                i = (i + 2);
            }
            return ((int)(ExpressionParser._ChangeType(result, typeof(int))));
        }
        /// <summary>
        /// Evaluates a derivation of the form:
        /// Unary= ( "+" | "-" ) Unary | Leaf
        /// </summary>
        /// <remarks>
        /// The production rules are:
        /// Unary -> add Unary
        /// Unary -> sub Unary
        /// Unary -> Leaf
        /// </remarks>
        /// <param name="node">The <see cref="ParseNode"/> to evaluate</param>
        /// <param name="state">A user supplied state object. What it should be depends on the production's associated code block</param>
        /// <returns>The result of the evaluation</returns>
        internal static int EvaluateUnary(ParseNode node, object state) {
            if ((node.Children.Length == 1)) {
                return ((int)(ExpressionParser._ChangeType(ExpressionParser.EvaluateLeaf(node.Children[0], state), typeof(int))));
            }
            if ((node.Children[0].SymbolId == GloryDemo.ExpressionParser.add)) {
                return ((int)(ExpressionParser._ChangeType(ExpressionParser.EvaluateUnary(node.Children[1], state), typeof(int))));
            }
            else {
                return ((int)(ExpressionParser._ChangeType((0 - ExpressionParser.EvaluateUnary(node.Children[1], state)), typeof(int))));
            }
        }
        /// <summary>
        /// Evaluates a derivation of the form:
        /// Leaf= integer | identifier | "(" Term ")"
        /// </summary>
        /// <remarks>
        /// The production rules are:
        /// Leaf -> integer
        /// Leaf -> identifier
        /// Leaf -> lparen Term rparen
        /// </remarks>
        /// <param name="node">The <see cref="ParseNode"/> to evaluate</param>
        /// <param name="state">A user supplied state object. What it should be depends on the production's associated code block</param>
        /// <returns>The result of the evaluation</returns>
        internal static int EvaluateLeaf(ParseNode node, object state) {
            if ((node.Children.Length == 1)) {
                if ((node.Children[0].SymbolId == GloryDemo.ExpressionParser.integer)) {
                    return ((int)(ExpressionParser._ChangeType(node.Children[0].Value, typeof(int))));
                }
                else {
                    if ((state != null)) {
                        int val;
                        IDictionary<string, int> d = ((IDictionary<string, int>)(state));
                        if (d.TryGetValue(node.Children[0].Value, out val)) {
                            return ((int)(ExpressionParser._ChangeType(val, typeof(int))));
                        }
                    }
                    throw new System.Exception(string.Format("Reference to undefined variable {0}", node.Children[0].Value));
                }
            }
            else {
                return ((int)(ExpressionParser._ChangeType(ExpressionParser.EvaluateTerm(node.Children[1], state), typeof(int))));
            }
        }
        public const int Term = 0;
        public const int Factor = 1;
        public const int Unary = 2;
        public const int Leaf = 3;
        public const int TermList = 4;
        public const int FactorList = 5;
        public const int add = 6;
        public const int sub = 7;
        public const int mul = 8;
        public const int div = 9;
        public const int lparen = 10;
        public const int rparen = 11;
        public const int integer = 12;
        public const int identifier = 13;
        public const int whitespace = 14;
        public const int EosSymbol = 15;
        public const int ErrorSymbol = 16;
        private static object _ChangeType(object obj, System.Type type) {
            System.ComponentModel.TypeConverter typeConverter = System.ComponentModel.TypeDescriptor.GetConverter(obj);
            if (((null == typeConverter) 
                        || (false == typeConverter.CanConvertTo(type)))) {
                return System.Convert.ChangeType(obj, type);
            }
            return typeConverter.ConvertTo(obj, type);
        }
        private static object _EvaluateAny(ParseNode node, object state) {
            if ((node.SymbolId == ExpressionParser.Term)) {
                return ExpressionParser.EvaluateTerm(node, state);
            }
            if ((node.SymbolId == ExpressionParser.Factor)) {
                return ExpressionParser.EvaluateFactor(node, state);
            }
            if ((node.SymbolId == ExpressionParser.Unary)) {
                return ExpressionParser.EvaluateUnary(node, state);
            }
            if ((node.SymbolId == ExpressionParser.Leaf)) {
                return ExpressionParser.EvaluateLeaf(node, state);
            }
            if ((node.SymbolId == ExpressionParser.add)) {
                return node.Value;
            }
            if ((node.SymbolId == ExpressionParser.sub)) {
                return node.Value;
            }
            if ((node.SymbolId == ExpressionParser.mul)) {
                return node.Value;
            }
            if ((node.SymbolId == ExpressionParser.div)) {
                return node.Value;
            }
            if ((node.SymbolId == ExpressionParser.lparen)) {
                return node.Value;
            }
            if ((node.SymbolId == ExpressionParser.rparen)) {
                return node.Value;
            }
            if ((node.SymbolId == ExpressionParser.integer)) {
                return node.Value;
            }
            if ((node.SymbolId == ExpressionParser.identifier)) {
                return node.Value;
            }
            return null;
        }
    }
}
namespace GloryDemo {
    
}
