//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GloryDemo {
    using System.Collections.Generic;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Glory", "0.1.0.0")]
    internal class Test1Parser : GlrTableParser {
        internal static int[][][][] ParseTable = new int[][][][] {
                new int[][][] {
                        new int[][] {
                                new int[] {
                                        1}},
                        new int[][] {
                                new int[] {
                                        2}},
                        null,
                        new int[][] {
                                new int[] {
                                        5}},
                        null},
                new int[][][] {
                        null,
                        null,
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        -1}}},
                new int[][][] {
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        3}},
                        null,
                        new int[][] {
                                new int[] {
                                        0,
                                        0,
                                        1}}},
                new int[][][] {
                        null,
                        new int[][] {
                                new int[] {
                                        4}},
                        null,
                        new int[][] {
                                new int[] {
                                        5}},
                        null},
                new int[][][] {
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        3},
                                new int[] {
                                        1,
                                        1,
                                        1,
                                        2,
                                        1}},
                        null,
                        new int[][] {
                                new int[] {
                                        1,
                                        1,
                                        1,
                                        2,
                                        1}}},
                new int[][][] {
                        null,
                        null,
                        new int[][] {
                                new int[] {
                                        2,
                                        1,
                                        3}},
                        null,
                        new int[][] {
                                new int[] {
                                        2,
                                        1,
                                        3}}}};
        internal static string[] SymbolTable = new string[] {
                "S",
                "E",
                "Implicit",
                "Implicit2",
                "#EOS",
                "#ERROR"};
        internal static ParseAttribute[][] ParseAttributes = new ParseAttribute[][] {
                new ParseAttribute[] {
                        new ParseAttribute("start", true)},
                new ParseAttribute[0],
                new ParseAttribute[0],
                new ParseAttribute[0],
                new ParseAttribute[0],
                new ParseAttribute[0]};
        internal static int[] ErrorSentinels = new int[0];
        public Test1Parser(IEnumerable<Token> tokenizer) : 
                base(Test1Parser.ParseTable, Test1Parser.SymbolTable, Test1Parser.ParseAttributes, Test1Parser.ErrorSentinels, tokenizer, int.MaxValue) {
        }
        public Test1Parser(IEnumerable<Token> tokenizer, int maxErrorCount) : 
                base(Test1Parser.ParseTable, Test1Parser.SymbolTable, Test1Parser.ParseAttributes, Test1Parser.ErrorSentinels, tokenizer, maxErrorCount) {
        }
        public const int S = 0;
        public const int E = 1;
        public const int Implicit = 2;
        public const int Implicit2 = 3;
        public const int EosSymbol = 4;
        public const int ErrorSymbol = 5;
    }
}
namespace GloryDemo {
    
}
